name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hotsted
    steps:
      - uses: actions/checkout@v2
      - run: cd CICD && cd CICD && sudo docker-compose up
     
